### ISSUE TITLE
paper  ask

### ISSUE THREAD

**Issue by wanghangege** [awethaileslassie/ST_PointRCNN#1]
Have you finished the work yet? Looking forward to reading your paper

**Comment by gebawe** [comment]
Thank you for your interest in our paper. 
It has been published at [IEEE-RAL](https://ieeexplore.ieee.org/document/9968086) and presented at ICRA.
You can have the preprint open access here: [Teachers in concordance for pseudo-labeling of 3D sequential data](https://www.researchgate.net/publication/361981821_Teachers_in_concordance_for_pseudo-labeling_of_3D_sequential_data)

**Comment by wanghangege** [comment]
thank you very much !
